---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: {{HOMEPAGE_VAR_TITLE}}
theme: dark
background: https://raw.githubusercontent.com/gethomepage/homepage/main/docs/assets/blossom_valley.jpg
showStats: true

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}

layout:
  Media:
    style: row
    columns: 2
  Download:
    style: row
    columns: 3
  System:
    style: row
    columns: 3

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true