---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: {{HOMEPAGE_VAR_TITLE}}
theme: dark
background: https://images.unsplash.com/photo-1738831920727-73e17adc5b87?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
showStats: true

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}

layout:
  Media:
    style: row
    columns: 2
  Download:
    style: row
    columns: 3
  System:
    style: row
    columns: 3

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true