---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: {{HOMEPAGE_VAR_TITLE}}
theme: dark
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
showStats: true

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}

layout:
  Media:
    style: row
    columns: 2
  Download:
    style: row
    columns: 3
  Network:
    style: row
    columns: 2

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true